name: Build & Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend deps
        working-directory: ./backend
        run: |
          npm ci

      - name: Run tests (optional)
        working-directory: ./backend
        run: |
          npm test || echo "no tests"

      # Build / Artifact step - placeholder if you need
      - name: Build (placeholder)
        working-directory: ./backend
        run: |
          echo "Build step - add compile/build commands if needed"

      # Deploy step - add your provider-specific deploy commands
      - name: Deploy to Render / Railway / Your host
        if: always()
        run: |
          echo "Add your deploy commands here (rsync, docker push, render deploy, railway up, etc.)"
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          FLW_SECRET_KEY: ${{ secrets.FLW_SECRET_KEY }}
          FLW_WEBHOOK_SECRET: ${{ secrets.FLW_WEBHOOK_SECRET }}
